package com.danhy989.tradingstrategybot.Enums;

public enum PositionValueEnum {
    WAITING_BAR_COUNT_POSITION_VALUE,
    DEFAULT_POSITION_VALUE,
    OPEN_LONG_POSITION_VALUE,
    CLOSE_LONG_POSITION_VALUE,
    OPEN_SHORT_POSITION_VALUE,
    CLOSE_SHORT_POSITION_VALUE;
}
